service: get-start-express-typescript-lambda
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  logRetentionInDays: 30

package:
  patterns:
    - "!tests/**"
    - "!coverage/**"
    - "!requests/**"
    - "!local.*"
    - "!jest.*"

custom:
  serverless-offline:
    httpPort: 3333

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

  # api_url:
  #   handler: handler.handler
  #   timeout: 30
  #   memorySize: 512
  #   url:
  #     cors:
  #       allowedOrigins:
  #         - "*"
  #       allowedHeaders:
  #         - "*"
  #       allowedMethods:
  #         - "*"
